version: "3.8"
services:
  login:
    build:
      context: D:\Documentos\proyecto progra 2024 bitbucket\codigo\Backend
      dockerfile: login.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
  db:
    build:
      context: D:\Documentos\proyecto progra 2024 bitbucket\codigo\Database
      dockerfile: database.Dockerfile
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  apis:
    build:
      context: D:\Documentos\proyecto progra 2024 bitbucket\codigo\Backend
      dockerfile: apis.Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app-network

  subircertificado:
    build:
      context: D:\Documentos\proyecto progra 2024 bitbucket\codigo\Backend
      dockerfile: subircertificado.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  estadisticas:
    build:
      context: D:\Documentos\proyecto progra 2024 bitbucket\codigo\Backend
      dockerfile: estadisticas.Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
