version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Ajusta el puerto según lo necesario
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Ajusta el puerto según lo necesario
    networks:
      - app-network
    depends_on:
      - database
    links:
      - database:database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306" # Ajusta el puerto según lo necesario
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  app-network:
    driver: bridge
